services:
  - type: web
    name: job-tracker-api
    env: docker            
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: warning
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_ENCRYPT
        value: true
      - key: SANCTUM_STATEFUL_DOMAINS
        scope: runtime
      - fromGroup: job-tracker-api-env

envGroups:
  - name: job-tracker-api-env
    envVars:
      - key: APP_NAME
        value: HireSight
      - key: APP_URL
        scope: runtime
      - key: FRONTEND_URL
        scope: runtime
      - key: APP_KEY
        scope: runtime
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        scope: runtime
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        scope: runtime
      - key: DB_USERNAME
        scope: runtime
      - key: DB_PASSWORD
        scope: runtime
      - key: MYSQL_ATTR_SSL_CA                 
        value: /var/www/html/database/certs/ca.pem         
      - key: GEMINI_API_KEY
        scope: runtime
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: GEMINI_API_URL
        value: https://generativelanguage.googleapis.com/v1beta/models